Feature/pratyush1718/navbar
TritonSE/DFM-Sideline-Sidekick-App pull request #14
Opened 2024-02-10 18:50 UTC by pratyush1718

## Tracking Info

Resolves #3 

## Changes

Add a bottom nav bar component per figma designs. Also added stack navigation for different button clicks on the nav bar.

## Testing

Tested using android emulator, ss below

- TODO

<img width="381" alt="image" src="https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/54123007/731dc792-e093-47ef-b1ae-cbe8fe60eab0">

2024-02-11 05:04 UTC, Anthonyp0329 requested changes
Looks amazing, thanks for the great work! Just a few minor things I commented about, and try to resolve linter issues as well, lmk if you need help.

2024-02-11 05:04 UTC, Anthonyp0329 commented on dfm-sideline-sidekick-app/components/bar.tsx
> +  const styles = StyleSheet.create({
Put styles into a separate file from the component itself

2024-02-11 05:04 UTC, Anthonyp0329 commented on dfm-sideline-sidekick-app/pages/HomePage.tsx
Our home page is actually just going to be the global search page, so just make the home page be the search page and feel free to delete this page

2024-02-13 03:29 UTC, EdwardLinS commented on dfm-sideline-sidekick-app/icons/circleIcon.tsx
> +const styles = StyleSheet.create({
Not sure if it's necessary as it's such a small style sheet, but for consistency's sake, it might be good to move this to its own file as well.

2024-02-13 03:30 UTC, EdwardLinS approved these changes
Other than needing to move the style sheets to new files, everything looks great! Good job!

2024-02-15 04:44 UTC, r800360 requested changes
I apologize for the delay in reviewing this. Nice work with these changes; I tried it out on my Android device and got good results, but on my iPad, I saw that the search icon was not aligned properly. A photo is attached below. 
![NavBar Feature iPad Test - Sachdeva, Rohan](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/87f38ebe-874e-4891-96ee-02d7fa831e41)

I went ahead and fixed some of the annoying linter issues, and I'll see if I can take care of the package.json/package-lock.json issues; hopefully more do not pop up. I think the pending issues to focus on as discussed previously are:
1. Making separate files for the styles in the Stylesheets
2. Change home page to global search page
3. iPad issue described here

Otherwise, very well done!

2024-02-15 05:47 UTC, r800360 commented
Alright linter issues and package.json/package-lock.json merge conflict are all taken care of, so this concludes my commits to the branch as of now.

2024-02-17 03:40 UTC, r800360 approved these changes
It seems that you completed the necessary changes of making a separate file for the bar's Stylesheet and deleting the HomePage. We will fix the iPad issue later. I'll approve the changes!

2024-02-20 23:10 UTC, Anthonyp0329 approved these changes
Looking great, thanks!

2024-02-21 00:48 UTC, merged