General principles main view
TritonSE/DFM-Sideline-Sidekick-App pull request #24
Opened 2024-03-07 04:40 UTC by r800360

## Tracking Info

Resolves #17 

## Changes

Implement the discussed page by passing a title prop to the GlobalSearch SearchBarComponent for the top section, with Browse By Category subheader/subtitle, and a two column grid of Pressable components below that also integrates scrolling functionality. Rewrote styles for Global Search to use device dimensions (as opposed to fixed hardcoded values); wrote General Principles to use device dimensions in conjunction with precise Figma measurements for devices of varying size.

## Testing

We confirmed that the changes worked by deploying on a mobile phone and to confirm layout as well as baseline search and scrolling functionality. You can test this change by pressing on the bottom right button of the three buttons on the navbar below and looking at the layout while trying out scrolling and search. Currently, buttons do not have any functionality yet.

## Confirmation of Change

Screenshots are attached below that illustrate adaptation between phone and iPad/tablet and some accommodation of varying device sizes while remaining in the two column format prescribed by the designers. Format is phone first then iPad and one photo each of top, bottom, and search:

![Screenshot_20240306_202232_Expo Go](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/db4cafdc-5f32-4460-8e13-08c50a096576)
![Screenshot_20240306_202245_Expo Go](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/3541a221-21ab-4520-9cb3-b50ad4da6ea4)
![Screenshot_20240306_202954_Expo Go](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/acf09c38-f7ae-496c-a7dd-d79558bf0c3a)
![IMG_8508](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/0e938b29-12b8-4bac-ba74-4a8673cc52dc)
![IMG_8509](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/fafa42d7-af55-4ea5-b5c3-19585dec2636)
![IMG_8507](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/78710b0b-65bc-4914-9f07-4b3eb49055f0)

2024-03-08 06:17 UTC, meganleongg requested changes
I'm using an Iphone 15 emulator and I noticed that "General Principles" and "Browse by Category" seem like they're of the wrong font weight/size. They look mismatched from the Figma designs--I don't think rewriting the styles to integrate device dimensions is accurate as of now. The pressable components also seem to be currently centering the titles, but the Figma designs are left-top-aligned and have a taller overall height for each box. 

what my emulator shows:
<img width="342" alt="Screenshot 2024-03-07 at 10 13 44 PM" src="https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/98578642/969ca604-d840-4282-95aa-cd32d910f590">

figma design:
<img width="418" alt="Screenshot 2024-03-07 at 10 14 38 PM" src="https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/98578642/fa988aa8-be86-4f8f-88de-cc40e9f9e8ee">

2024-03-11 01:18 UTC, PiXlRAM approved these changes
Tested on my iphone and android simulator, LGTM. Don't have a larger device to test on but refer to Megan's feedback for the issues with displaying on larger screens.

2024-03-11 04:29 UTC, Anthonyp0329 approved these changes
Code looks great! Just address the visual issues Megan noticed, as well as any comments the designers made, but should be good to merge.

2024-03-14 06:42 UTC, meganleongg approved these changes

2024-03-14 06:45 UTC, merged