Feature/pratyush1718/bookmark component
TritonSE/DFM-Sideline-Sidekick-App pull request #27
Opened 2024-03-09 16:55 UTC by pratyush1718

## Tracking Info

Resolves #15 

## Changes

Added AsyncStorage functionality to store names of bookmarked pages, added a bookmark component to emergency and general principles page to leverage said functionality

## Testing

Added console log statements for bookmark routes and tested component on android emulator

## Confirmation of Change

![image](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/54123007/f4d4ab0d-b4ae-45fa-812d-a49d4f70c9cd)
![image](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/54123007/82d3efb4-db69-4042-b3af-62501f124e44)

2024-03-12 03:41 UTC, Anthonyp0329 requested changes
Looking awesome, great work! Just make sure to add this to the ConditionsSection.tsx page as well.

2024-03-12 03:41 UTC, Anthonyp0329 commented on dfm-sideline-sidekick-app/components/bookmarkRoutes.js
> +// Function for testing to clear all bookmarks from AsyncStorage
can remove this code for merging

2024-03-12 20:55 UTC, Anthonyp0329 approved these changes

2024-03-15 01:40 UTC, r800360 approved these changes
I went ahead and changed the bookmarkRoutes.js to a .tsx file and created the Bookmark type to fix all the linter issues that were popping up with that file. I also switched TouchableOpacity to the industry standard Pressable in the bookmark.tsx. These changes look good to me and work on my end, but be sure to check that everything works as expected and fix any unresolved issues that Anthony mentioned. Nice work on this!

2024-03-15 18:54 UTC, EdwardLinS approved these changes
Good job Pratyush! It looks good to me. Tested different bookmarks on iPad and Android devices and they all seem to work. Other than the things Anthony said, seems ready to merge.

2024-03-26 19:25 UTC, merged