Categories page
TritonSE/DFM-Sideline-Sidekick-App pull request #44
Opened 2024-05-14 09:13 UTC by EdwardLinS

## Tracking Info

Resolves #36 

## Changes

- Added the emergency and general principle category pages to display all categories under each
- Added the all pages page to show all pages and which category they belong to
- Allow deletion of categories and pages
- Create a toast to confirm deletion of categories

## Testing

- Tested fetching each category
- Tested fetching each page
- Testing deleing pages and categories
- Changed the size of the window to test responsiveness

## Confirmation of Change

![image](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/63514282/a9e8bea2-f691-4ad9-9736-222364f9338c)
![image](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/63514282/aaf8c846-f154-4077-8751-363285599d21)
![image](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/63514282/001f2da0-1e0c-4246-8576-f0543dac12de)
![image](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/63514282/5919447f-2009-47bc-acdb-5dcc068a3683)

2024-05-15 23:52 UTC, eshaan-s18 approved these changes
This is awesome! Great job! The dynamic fetching and displaying of all the categories works great for me. The pages look great and follow the Figma well! Also the resizing of the window feature looks great too! The delete button on the Emergencies and General Principles pages work seamlessly; the only thing I noticed was that the delete button on the All Pages page doesn't seem to be functioning for me. Not sure if this was intended or not. I'll approve this PR though because everything else is working great and making the delete button work shouldn't be too challenging as you have it already implemented on the other pages. If this was intentional though, then everything looks good to me! Great job team!

2024-05-16 20:34 UTC, Anthonyp0329 approved these changes
Awesome work guys!! Looks good to go!! For the purposes of merging into main, make sure to update the branch with latest commits, and you can get rid of the changes to the main page.tsx for now. @pratyush1718 will take care of having the navbar route to the appropriate page. Thanks!!

2024-05-16 20:34 UTC, Anthonyp0329 commented on admin-portal-frontend/src/app/components/categoryRoutes.tsx
> +    const url = "http://localhost:3001/api/categories";
have the url domain be stored in a .env, just for future production deployment and such

2024-05-21 16:15 UTC, r800360 requested changes
Awesome PR Edward and Lillian! Changes look great to me and using the recent environmental variable change, I'm able to connect in the hosted backend: https://sideline-sidekick-app.web.app/api/categories as well to fetch the data for the three pages: all-page, emergencies, general-principles. 

As Eshaan mentioned, could you investigate the issue with the delete button at the all-page (http://localhost:3000/all-page/)? Other than that, everything else looks good. Thanks in advance and sorry for the late review.

2024-05-29 04:30 UTC, r800360 approved these changes
Edward and Lillian, nice job fixing the delete button on the all-page as well as all of those nasty linter errors! This code looks good to merge to me.

2024-05-29 04:48 UTC, eshaan-s18 approved these changes
Looks good to me! Great job!

2024-05-29 21:31 UTC, Anthonyp0329 approved these changes
Looks good and ready to merge! Awesome work!

2024-06-04 01:35 UTC, merged