Emergency flow page
TritonSE/DFM-Sideline-Sidekick-App pull request #45
Opened 2024-05-17 01:02 UTC by r800360

## Tracking Info

Resolves #41 

## Changes

Designed the Emergency flow page and added functionality to enter into text fields and publish to MongoDB database

## Testing

To test, try entering into the text fields and click publish to send to MongoDB database.

A screenshot of the page is as follows:
![EmergencyFlowPage](https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/45048779/ebcdecbf-4148-4ead-a8ef-6439e0d63a15)

2024-05-17 21:53 UTC, Anthonyp0329 requested changes
Looking awesome! Just a few small things: when the user doesn't put anythgin under one of the optional fields, make sure to not include that field in the object that gets published into the database. Also - experiencing some small styling issues with the textinputs overlapping the navbar: 
<img width="1367" alt="image" src="https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/76824702/f7a895c2-52ff-4937-8d0e-bd1d40541fea">

2024-05-20 04:59 UTC, Anthonyp0329 commented
also just remembered, make sure to add a subtitle field at the top. This is the part that is displayed on the card for that emergency

2024-05-29 21:50 UTC, Anthonyp0329 requested changes
Almost ready to go! Just address the changes I noted, and also make sure to have some sort of error message notifying the user when a required field isn't filled out when they try to submit the form.

2024-05-29 21:50 UTC, Anthonyp0329 commented on admin-portal-frontend/emergencies.ts
Move this, as well as the requests.ts file into the src/app folder in a folder called api or something of the sort

2024-05-29 21:50 UTC, Anthonyp0329 commented on package.json
remove this

2024-05-29 21:50 UTC, Anthonyp0329 commented on admin-portal-frontend/emergencies.ts
> +    const response = await post("/api/emergencies", emergency);
make sure to have these routes depend on a .env file for local development purposes

2024-06-04 17:13 UTC, r800360 commented
Issues Addressed/Changelog:
-- when the user doesn't put anything under an optional field (any field not title or subtitle), field is not included in the object that gets published into the database

-- fixed styling issues with the textinputs overlapping the navbar

-- added subtitle field to the form

-- added error message notifying the user when a required field (title or subtitle) isn't filled out when they try to submit the form

-- moved emergencies.ts and requests.ts into src/app/api

-- remove head package.json (separate from other package.json files)

-- Created dependency between src/api/emergencies.ts (createEmergency(), getEmergency(), getAllEmergencies(), updateEmergency()) on local.env for the admin-portal-frontend

Thanks! Let me know if we missed anything.

2024-09-30 00:09 UTC, merged