Conditions Section Page
TritonSE/DFM-Sideline-Sidekick-App pull request #8
Opened 2024-01-29 02:46 UTC by LillianHo5

## Tracking Info

Resolves #4 

## Changes

We implemented the page showing information about medical emergencies. For now, we hardcoded the page information with the example provided on the Figma.

## Testing

We confirmed that our changes worked by running it on a variety of IOS and Android emulators, such as the Pixel 4a, iPhone 15 Pro Max, and iPhone 15. The implementation looked fine on all of these emulators. 

## Confirmation of Change

<img width="346" alt="Screenshot 2024-01-28 at 6 45 22 PM" src="https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/92070679/93a8880b-ca36-4ebf-91c6-a720281c7de0">

<img width="344" alt="Screenshot 2024-01-28 at 6 46 01 PM" src="https://github.com/TritonSE/DFM-Sideline-Sidekick-App/assets/92070679/fc3df291-f6c1-46ac-bfb5-94449e21f70d">

2024-01-30 00:32 UTC, Anthonyp0329 requested changes
Looks great overall! Make sure to put your styles into a separate file, and fix the linter warnings, VSCode should pop up some autofixes if you right click on the errors. Moving the styles into a separate file and importing it at the top should fix many of the errors.

2024-01-30 00:32 UTC, Anthonyp0329 commented on dfm-sideline-sidekick-app/ConditionsSection.tsx
> +const styles = StyleSheet.create({
Make a separate file called "ConditionSectionStyles.tsx" or something along those lines that contains the styles

2024-01-30 00:32 UTC, Anthonyp0329 commented on dfm-sideline-sidekick-app/App.tsx
No need to commit changes to this file, leave without changes as these changes are just for testing purposes

2024-01-30 00:32 UTC, Anthonyp0329 commented on dfm-sideline-sidekick-app/ConditionsSection.tsx
> +const styles = StyleSheet.create({
If you import styles from the file at the top of your file, this will fix many of the linter errors

2024-01-30 04:40 UTC, EdwardLinS approved these changes
Looks good to me! Other than the things that Anthony mentioned this is solid. Good job yall!

2024-01-31 03:27 UTC, r800360 approved these changes
The changes look good to me; well done! Be sure to implement the suggestions about the styles made by Anthony, and otherwise, keep up the good work!

One small thing that should be addressed later is that on Android everything seems to be running smoothly, but on iOS (iPad), I get from both VSCode and my device:
 ERROR  fontFamily "Roboto" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.


However, besides for the error message, this does not seem to cause much functional difference, and it seems like it should be a simple fix, so I'll approve the changes here.

2024-02-01 22:09 UTC, Anthonyp0329 approved these changes
Great job adjusting and fixing stuff, it's ready to merge!

2024-02-03 04:26 UTC, merged